/**************************************************************************/
/**********************    SEO Meta Descriptions   ************************/
/**************************************************************************/
export const title_main_page = "Mx Lyrics";
export const meta_description = "Musixverse will bring Artists and Fans together like never before and unlock novel models of communications and commerce.";

export const genreArray = [
	"Acoustic",
	"Alternative",
	"Anime",
	"Big Band",
	"Blues",
	"Children’s Music",
	"Classical",
	"Comedy",
	"Commercial",
	"Contemporary",
	"Country",
	"Dance",
	"Dance-pop",
	"Disney",
	"Easy Listening",
	"Electronic",
	"Enka",
	"French Pop",
	"Folk",
	"Genreless",
	"German Folk",
	"German Pop",
	"Fitness & Workout",
	"Hip-Hop",
	"Holiday",
	"Indie Folk",
	"Indie Pop",
	"Industrial",
	"Inspirational",
	"Instrumental",
	"J-Pop",
	"Jazz",
	"Jingles",
	"K-Pop",
	"Karaoke",
	"Kayokyoku",
	"Latin",
	"Lo-fi",
	"Lullabies",
	"Metal",
	"Musical",
	"New Age",
	"Opera",
	"Pop",
	"Post-Disco",
	"Progressive",
	"Punk",
	"R&B",
	"Rap",
	"Reggae",
	"Rock",
	"Soundtrack",
	"Spoken Word",
	"Stories",
	"Tex-Mex/Tejano",
	"Vocal",
];
export const languageArray = [
	"Hindi",
	"English",
	"English, Hindi",
	"Arabic",
	"Armenian",
	"Assamese",
	"Awadhi",
	"Bengali",
	"Bhojpuri",
	"Chinese",
	"Czech",
	"Danish",
	"Dutch",
	"English",
	"Filipino",
	"Finnish",
	"French",
	"German",
	"Greek",
	"Gujarati",
	"Haryanvi",
	"Hebrew",
	"Hindi",
	"Hungarian",
	"Icelandic",
	"Indonesian",
	"Irish",
	"Italian",
	"Japanese",
	"Kannada",
	"Kashmiri",
	"Konkani",
	"Korean",
	"Malayalam",
	"Maltese",
	"Mandarin",
	"Marathi",
	"Nepali",
	"Odia",
	"Pahari",
	"Persian",
	"Polish",
	"Portuguese",
	"Punjabi",
	"Rajasthani",
	"Romanian",
	"Russian",
	"Serbian",
	"Spanish",
	"Swedish",
	"Tamil",
	"Telugu",
	"Thai",
	"Turkish",
	"Ukrainian",
	"Urdu",
];
